version: '2'
services:


# ### Data container: downloads and session data ##############
    data:
        image: busybox
        volumes:
            - /mnt/pool/TEST/:/rtorrent

# ### ruTorrent (front end) Container #########################

    rutorrent:
        build: ./web

# ### HHVM Container #########################################

    hhvm:
        build: ./HHVM
        volumes:
            - ./storage/logs/hhvm:/var/log/hhvm
        ports:
            - "24503:24503"
        environment:
            NGINX_HOST: "nginx"
        volumes_from:
            - rutorrent
            - data
        networks:
            main:
                aliases:
                  - hhvm

# ### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        volumes:
            - ./storage/logs/nginx:/var/log/nginx
        ports:
            - "88:80"
        links:
            - hhvm
        volumes_from:
            - rutorrent
            - data

        networks:
            main:
                aliases:
                   - nginx

# ### irssi Container #########################################

    irssi:
        build: ./irssi
        volumes:
            - /mnt/pool/TEST/watch/:/home/user/watch:rw
        tty: true
        expose:
            - "27096"
        networks:
            main:
                aliases:
                   - irssi

networks:
  main:
